### ISSUE TITLE
Header log in / sign up links wrap on iPhone SE

### ISSUE THREAD

**Issue by mknadler** [components-ai/issues#1]
This is obviously a minor bug (and a common one!), but, from a small-phone-haver, thought you might want to know that your login + signup links are wrapping on my device. Seen in iOS Safari & Brave on an iPhone SE.

![1E3C496D-CE14-4938-B7A0-0A64D8CD2597](https://user-images.githubusercontent.com/3596891/117899592-6f2ca480-b295-11eb-9d40-6e5f983edaa4.png)

**Comment by mrmrs** [comment]
@mknadler Thank you for the bug report!

**Comment by mrmrs** [comment]
![iphone-se-fix](https://user-images.githubusercontent.com/1748143/118530728-f903c400-b712-11eb-8e83-e4584f65c1a5.png)
 
@mknadler I haven't been able to test this on an actual device but believe this should be fixed now after testing on emulators. 
Thank you again for the bug report! Closing for now but feel free to reopen if it doesn't indeed fix the issue on your end.
