### ISSUE TITLE
TypeError: null is not an object (evaluating 'e.profile.avatarUrl')

### ISSUE THREAD

**Issue by aqrln** [components-ai/issues#3]
Hi! I created an account using the email login flow, signed in for the first time, clicked the link to my profile in the top right corner, and this error occurred:

<img width="1437" alt="image" src="https://user-images.githubusercontent.com/4923335/127714401-ad5aef9d-a71c-42c4-868a-f20a4c40ce01.png">

As far as I can tell, there's a check for `e` being nullish, but it's `e.profile` itself that is `null`.

<img width="1070" alt="image" src="https://user-images.githubusercontent.com/4923335/127715116-24ea7af4-90f2-4058-b3b5-2b9a72ad0a26.png">

Browser: Safari 14.1.1 (16611.2.7.1.4), macOS 11.4

---

UPD: This only happened once, couldn't reproduce after reloading the page a bunch of times.

**Comment by johno** [comment]
Thanks for reporting! I forgot to circle back here but we deployed a fix a while back : )
