### ISSUE TITLE
Delete components on user page

### ISSUE THREAD

**Issue by pwflint** [components-ai/issues#9]
It would be nice to be able to delete components off the user page, particularly as nav menu items generate pages while becoming familiar with the user interface.

PWF

**Comment by pwflint** [comment]
Managed to figure this out via settings on individual pages (web dev amateur, thanks for being patient). Would comment that the UX is a little frustrating. A little trashcan next to each component on the dashboard would be nice.

**Comment by mrmrs** [comment]
@pwflint thanks for the suggestion - definitely want to hit batch actions in the future.
